# latest stable Node.js release
language: node_js
node_js: node

# cache the node modules
cache:
  directories:
    - node_modules

# build notification
notifications:
  email:
  - oliverwilliams345@gmail.com

# Restrict builds on branches
branches:
  only:
    - master

script: 'npm run build'

# build notification
notifications:
  email:
  - oliverwilliams345@gmail.com

# Environment variables
env:
  global:
    - CHANGED_FILES=$(git diff --name-only $TRAVIS_COMMIT_RANGE)

# Auto-publish to NPM
after_success:
  - 'if [[ $TRAVIS_PULL_REQUEST = "false" ]]; then PUBLISH_PACKAGE=true; else PUBLISH_PACKAGE=false; fi'
  - 'echo "Pull Request: $TRAVIS_PULL_REQUEST" && echo "Node: $TRAVIS_NODE_VERSION" && echo "Publish? $PUBLISH_PACKAGE"'
  - 'if [ $PUBLISH_PACKAGE = "true" ]; then npm run publish; fi'
